name: Lint AXANET

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar flake8
        run: flake8 src tests
      - name: Mensaje de validación
        run: echo "El código cumple reglas básicas de estilo."
